<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />

    <ItemGroup>
        <ProjectReference Include="..\..\rbac\Yi.Framework.Rbac.Application\Yi.Framework.Rbac.Application.csproj" />
        <ProjectReference Include="..\..\setting-management\Yi.Framework.SettingManagement.Application\Yi.Framework.SettingManagement.Application.csproj" />
        <ProjectReference Include="..\..\tenant-management\Yi.Framework.TenantManagement.Application\Yi.Framework.TenantManagement.Application.csproj" />
        <ProjectReference Include="..\Demo.Domain\Demo.Domain.csproj" />
        <ProjectReference Include="..\Demok.Application.Contracts\Demo.Application.Contracts.csproj" />
    </ItemGroup>

</Project>
