<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <Folder Include="Entities\"/>
        <Folder Include="EventHandlers\"/>
        <Folder Include="Managers\"/>
        <Folder Include="Repositories\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\audit-logging\Yi.Framework.AuditLogging.Domain\Yi.Framework.AuditLogging.Domain.csproj"/>
        <ProjectReference Include="..\..\rbac\Yi.Framework.Rbac.Domain\Yi.Framework.Rbac.Domain.csproj"/>
        <ProjectReference Include="..\..\setting-management\Yi.Framework.SettingManagement.Domain\Yi.Framework.SettingManagement.Domain.csproj"/>
        <ProjectReference Include="..\..\tenant-management\Yi.Framework.TenantManagement.Domain\Yi.Framework.TenantManagement.Domain.csproj"/>
        <ProjectReference Include="..\FileDock.Domain.Shared\FileDock.Domain.Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Volo.Abp.Core" Version="8.3.4"/>
    </ItemGroup>

</Project>
