<Project Sdk="Microsoft.NET.Sdk">
    <Import Project="..\..\..\common.props" />

    <ItemGroup>
        <ProjectReference Include="..\..\audit-logging\Yi.Framework.AuditLogging.SqlSugarCore\Yi.Framework.AuditLogging.SqlSugarCore.csproj" />
        <ProjectReference Include="..\..\rbac\Yi.Framework.Rbac.SqlSugarCore\Yi.Framework.Rbac.SqlSugarCore.csproj" />
        <ProjectReference Include="..\..\setting-management\Yi.Framework.SettingManagement.SqlSugarCore\Yi.Framework.SettingManagement.SqlSugarCore.csproj" />
        <ProjectReference Include="..\..\tenant-management\Yi.Framework.TenantManagement.SqlSugarCore\Yi.Framework.TenantManagement.SqlSugarCore.csproj" />
        <ProjectReference Include="..\Demo.Domain\Demo.Domain.csproj" />
    </ItemGroup>

</Project>
